#!/usr/bin/env python3
from music21 import converter, stream
import os

def combine_parts(file_list, output_file):
    # Create a new Score object to combine all parts
    combined_score = stream.Score()

    # Iterate over each file in the file list
    for file_path in file_list:
        # Read the MusicXML file into a Stream object
        try:
            part = converter.parse(file_path)
            
            # Ensure we're dealing with a single part, not a full score
            if isinstance(part, stream.Score):
                part = part.parts[0]  # Extract the first (and only) part if needed
            
            # Append the part to the combined score
            combined_score.append(part)
        except Exception as e:
            print(f"Error parsing {file_path}: {e}")

    # Save the combined score to a new MusicXML file
    combined_score.write('musicxml', fp=output_file)
    print(f"Combined sheet saved to {output_file}")

# Example usage:
# List of MusicXML files generated by your script
# Get the list of MusicXML files in the musescore folder
musescore_folder = 'messages'
input_files = [os.path.join(musescore_folder, f) for f in os.listdir(musescore_folder) if f.endswith('.musicxml')]
#input_files = ['musescore/output.musicxml','musescore/output.musicxml', 'musescore/output2.musicxml']  # Replace with your actual file paths
output_file = 'musescore/combined_sheet.musicxml'

combine_parts(input_files, output_file)
