users:
  - default
  - name: vmuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBW+9xzr+wICQv/PpyR2cIakoCwSniFil299ExWg3Qlie4tOD8AxlffZJUeiuHmqwhOgF1xpmlSun8O+2WdC5Lf7Plsg28vlB2Fdt07h+BJYdAkhV3mxxc0yeuNT+03sGD7SpE6DTNY7D27UhV/KD92c0cneKi63C/RlqXMgK/OrPcbvcLyO2SJJyuuDZ2V1nycf99+jvsOz7xouvr/DRO/pBvRd5AxfPoYzXTHGKwO9ImNc5okbWieea9iT8T9vallKx25YfqKTWrKVi5JPg4IbutJ0hXrzbmxP0VpH4YCQN/Df2x1UQWaA8jdMx3caMgb4NeAISX/trwxp8xRqWowNe9mHDV2abEJrQ8jAIivJL0U5gmG+HD1ynSaLjJKHqvnujkarzJH9O1WFn1aeTKutCLFDyQP71tsjUoixKLWmuvmtKJNtg2F3K/1ffdno6GntZDwFXDCm+yh/SDmr5iueSesVg9R7lSxshSBglgVrloslQfwrJpkvKVEjGdu5U= vmuser
 